### ISSUE TITLE
Highlight blob string

### ISSUE THREAD

**Issue by mkushakov** [Tchoupinax/tilt-vscode-extension#10]
Add support for triple quoted blob:
```
# If for some reason you have YAML as a string, wrap it as a
# Blob so we know to treat it as DATA and not as a filepath
yaml_str = """
apiVersion: v1
kind: Pod
  metadata:
    name: nginx
    labels:
      app: nginx"""
```
Current behavior:
![image](https://user-images.githubusercontent.com/33716748/127290286-d3bbe919-472c-487a-a63a-898006a998f7.png)
